apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: win2022pa4
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-small
  # http or https location of OVA without the prefix:
  # imageName: ent.box.com/shared/static/7tpkzdl797pn4ty0e30yzaxsgkavj2gc.ova # win10jp
  # imageName: ent.box.com/shared/static/5h3zcyattwgoyt7crgakwdcreiviegpp.ova # win2022 original
  imageName: ent.box.com/shared/static/qtxzu2fv3jm2fcfest0wwd1gcnf3v8b6.ova # win2022 with pa
  powerState: poweredOn
  vmMetadata:
    secretName: sysprep-bootstrap-data
    transport: Sysprep
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"

---
apiVersion: v1
kind: Secret
metadata:
  name: sysprep-bootstrap-data
  namespace: default
stringData:
  unattend: |
    <?xml version="1.0" encoding="utf-8"?>
    <unattend xmlns="urn:schemas-microsoft-com:unattend">
        <settings pass="oobeSystem">
            <!-- Change Administrator Password -->
            <UserAccounts>
                <AdministratorPassword>
                    <Value>NewPassword123!</Value>
                    <PlainText>true</PlainText>
                </AdministratorPassword>
            </UserAccounts>

            <!-- Skip OOBE Setup for Simplicity -->
            <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <NetworkLocation>Work</NetworkLocation>
                <ProtectYourPC>1</ProtectYourPC>
            </OOBE>
        </settings>

        <settings pass="specialize">
            <!-- Enable Remote Desktop -->
            <Component name="Microsoft-Windows-TerminalServices-LocalSessionManager" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
                <fDenyTSConnections>false</fDenyTSConnections> <!-- False means Remote Desktop is enabled -->
            </Component>

            <!-- Configure Firewall for Remote Desktop -->
            <Component name="Microsoft-Windows-Firewall-GroupPolicy" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
                <DomainProfile>
                    <EnableFirewall>true</EnableFirewall>
                    <RemoteDesktop>
                        <Enabled>true</Enabled>
                    </RemoteDesktop>
                </DomainProfile>
                <StandardProfile>
                    <EnableFirewall>true</EnableFirewall>
                    <RemoteDesktop>
                        <Enabled>true</Enabled>
                    </RemoteDesktop>
                </StandardProfile>
            </Component>
        </settings>

        <!-- Set the computer name and time zone to JST -->
        <settings pass="specialize">
            <ComputerName>WS2022-Server</ComputerName>
            <TimeZone>Tokyo Standard Time</TimeZone> <!-- Japan Standard Time -->
        </settings>

    </unattend>
