apiVersion: v1
kind: Service
metadata:
  labels:
    app: llm-frontend
  name: llm-frontend
  namespace: llm
spec:
  ports:
    - name: "8501"
      port: 8501
      protocol: TCP
      targetPort: 8501
      nodePort: 30850
  selector:
    app: llm-frontend
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llm-frontend
  name: llm-frontend
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: llm-frontend
    spec:
      containers:
        - image: shogokobayashi/llm-frontend
          imagePullPolicy: Always
          name: llm-frontend
          ports:
            - containerPort: 8501
              protocol: TCP
          env:
            - name: LLM_HOST
              value: qwen2-1-5b.llm.svc.cluster.local:8000