apiVersion: v1
kind: Namespace
metadata:
  name: llm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qwen2-1-5b
  name: qwen2-1-5b
  namespace: llm
spec:
  ports:
    - name: "8000"
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30800
  selector:
    app: qwen2-1-5b
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qwen2-1-5b
  name: qwen2-1-5b
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen2-1-5b
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qwen2-1-5b
    spec:
      containers:
        - image: shogokobayashi/qwen2-1.5b
          imagePullPolicy: Always
          name: qwen2-1-5b
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}