apiVersion: v1
kind: Service
metadata:
  labels:
    app: objdetect-frontend
  name: objdetect-frontend
  namespace: objdetect
spec:
  ports:
    - name: "8501"
      port: 8501
      protocol: TCP
      targetPort: 8501
      nodePort: 30850
  selector:
    app: objdetect-frontend
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: objdetect-frontend
  name: objdetect-frontend
  namespace: objdetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objdetect-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: objdetect-frontend
    spec:
      containers:
        - image: shogokobayashi/demo-objdetect-frontend
          imagePullPolicy: Always
          name: objdetect-frontend
          ports:
            - containerPort: 8501
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: http://objdetect-backend.objdetect.svc.cluster.local:8000
