apiVersion: v1
kind: Namespace
metadata:
  name: db

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgre-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/postgre-pv"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-customtable-cm
  namespace: db
data:
  create_table.sql: |
    CREATE TABLE devicestatus (
       id SERIAL NOT NULL,
       devicename VARCHAR(255) NOT NULL,
       devicevalue DECIMAL NOT NULL,
       timestamp TIMESTAMP NOT NULL DEFAULT NOW()
    );

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: posgresql
    version: "v0.0.4"
  name: postgresql
  namespace: db
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        version: "v0.0.4"
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: postgresql
          image: bitnami/postgresql
          env:
            - name: POSTGRESQL_USERNAME
              value: "ecs_user"
            - name: POSTGRESQL_PASSWORD
              value: "VMware123"
            - name: POSTGRESQL_DATABASE
              value: "monitoring_db"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgre-pv
            - mountPath: /docker-entrypoint-initdb.d
              name: create-customtable
      volumes:
        - name: postgre-pv
          persistentVolumeClaim:
            claimName: postgre-pvc
        - name: create-customtable
          configMap:
            name: create-customtable-cm
            items:
            - key: create_table.sql
              path: create_table.sql
          
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: db
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgresql
  type: ClusterIP
